import Head from "next/head";
import Image from "next/image";

import "@/styles/globals.css";
import Nav from "@/compenents/Nav";
import Hero from "@/compenents/Hero";
import Services from "@/compenents/Services";
import ServicesData from "@/data/servicesCardData";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Nav />

        <main>
          <Hero />
          <section className="services">
            <h1>Services</h1>
            <div className="services-container">
            {ServicesData &&
              ServicesData.map((service) => (
                <Services
                  key={service.id}
                  title={service.title}
                  image={service.image}
                  description={service.description}
                  button={service.button}
                />
              ))}
            ;
            </div>
          </section>
        </main>
      </body>
    </>
  );
}
